package au.edu.unsw.soacourse.marketdatautil;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.0.4
 * 2015-04-17T16:08:01.055+10:00
 * Generated source version: 3.0.4
 * 
 */
@WebService(targetNamespace = "http://marketdatautil.soacourse.unsw.edu.au", name = "MarketDataUtilService")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface MarketDataUtilService {

    @WebResult(name = "currencyConvertMarketDataResponse", targetNamespace = "http://marketdatautil.soacourse.unsw.edu.au", partName = "parameters")
    @WebMethod(action = "http://marketdatautil.soacourse.unsw.edu.au/currencyConvertMarketData")
    public CurrencyConvertMarketDataResponse currencyConvertMarketData(
        @WebParam(partName = "parameters", name = "currencyConvertMarketDataRequest", targetNamespace = "http://marketdatautil.soacourse.unsw.edu.au")
        CurrencyConvertMarketDataRequest parameters
    ) throws CurrencyConvertMarketDataFaultMsg;

    @WebResult(name = "summariseMarketDataResponse", targetNamespace = "http://marketdatautil.soacourse.unsw.edu.au", partName = "parameters")
    @WebMethod(action = "http://marketdatautil.soacourse.unsw.edu.au/summariseMarketData")
    public SummariseMarketDataResponse summariseMarketData(
        @WebParam(partName = "parameters", name = "summariseMarketDataRequest", targetNamespace = "http://marketdatautil.soacourse.unsw.edu.au")
        SummariseMarketDataRequest parameters
    ) throws SummariseMarketDataFaultMsg;

    @WebResult(name = "visualiseMarketDataResponse", targetNamespace = "http://marketdatautil.soacourse.unsw.edu.au", partName = "parameters")
    @WebMethod(action = "http://marketdatautil.soacourse.unsw.edu.au/visualiseMarketData")
    public VisualiseMarketDataResponse visualiseMarketData(
        @WebParam(partName = "parameters", name = "visualiseMarketDataRequest", targetNamespace = "http://marketdatautil.soacourse.unsw.edu.au")
        VisualiseMarketDataRequest parameters
    ) throws VisualiseMarketDataFaultMsg;
}
