
package au.edu.unsw.soacourse.marketdatautil;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.0.4
 * 2015-04-17T16:08:01.050+10:00
 * Generated source version: 3.0.4
 */

@WebFault(name = "summariseMarketDataFault", targetNamespace = "http://marketdatautil.soacourse.unsw.edu.au")
public class SummariseMarketDataFaultMsg extends Exception {
    
    private au.edu.unsw.soacourse.marketdatautil.ServiceFaultType summariseMarketDataFault;

    public SummariseMarketDataFaultMsg() {
        super();
    }
    
    public SummariseMarketDataFaultMsg(String message) {
        super(message);
    }
    
    public SummariseMarketDataFaultMsg(String message, Throwable cause) {
        super(message, cause);
    }

    public SummariseMarketDataFaultMsg(String message, au.edu.unsw.soacourse.marketdatautil.ServiceFaultType summariseMarketDataFault) {
        super(message);
        this.summariseMarketDataFault = summariseMarketDataFault;
    }

    public SummariseMarketDataFaultMsg(String message, au.edu.unsw.soacourse.marketdatautil.ServiceFaultType summariseMarketDataFault, Throwable cause) {
        super(message, cause);
        this.summariseMarketDataFault = summariseMarketDataFault;
    }

    public au.edu.unsw.soacourse.marketdatautil.ServiceFaultType getFaultInfo() {
        return this.summariseMarketDataFault;
    }
}
